const imageManifest = [
  {
    name: 'america-chavez_200.png',
    path: 'src/img/america-chavez_200.png',
    sha: '021b1e493181ed82e4fe2da8d73ef108dce07571',
    size: 83149,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/america-chavez_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/america-chavez_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/021b1e493181ed82e4fe2da8d73ef108dce07571',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/america-chavez_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/america-chavez_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/021b1e493181ed82e4fe2da8d73ef108dce07571',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/america-chavez_200.png',
    },
  },
  {
    name: 'america-chavez_32_c.png',
    path: 'src/img/america-chavez_32_c.png',
    sha: '451cee0c3f92c333c898561f930f10ae2a039ff9',
    size: 2431,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/america-chavez_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/america-chavez_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/451cee0c3f92c333c898561f930f10ae2a039ff9',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/america-chavez_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/america-chavez_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/451cee0c3f92c333c898561f930f10ae2a039ff9',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/america-chavez_32_c.png',
    },
  },
  {
    name: 'amihan_200.png',
    path: 'src/img/amihan_200.png',
    sha: 'db22af4eaa1c44c9b00f27bba85470e549ee838f',
    size: 94410,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/amihan_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/amihan_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/db22af4eaa1c44c9b00f27bba85470e549ee838f',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/amihan_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/amihan_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/db22af4eaa1c44c9b00f27bba85470e549ee838f',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/amihan_200.png',
    },
  },
  {
    name: 'amihan_32_c.png',
    path: 'src/img/amihan_32_c.png',
    sha: 'a0017a18e37b60b2f9356827cd9b4462133823d3',
    size: 2723,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/amihan_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/amihan_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a0017a18e37b60b2f9356827cd9b4462133823d3',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/amihan_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/amihan_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a0017a18e37b60b2f9356827cd9b4462133823d3',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/amihan_32_c.png',
    },
  },
  {
    name: 'apple.png',
    path: 'src/img/apple.png',
    sha: '1d9b3ed15cacf664ec711e194e388461162b5b0b',
    size: 15842,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/apple.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/apple.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/1d9b3ed15cacf664ec711e194e388461162b5b0b',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/apple.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/apple.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/1d9b3ed15cacf664ec711e194e388461162b5b0b',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/apple.png',
    },
  },
  {
    name: 'apple_200.png',
    path: 'src/img/apple_200.png',
    sha: 'd759ee42e143ec5bcd5a806c71b4037dc1384a6f',
    size: 18894,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/apple_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/apple_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d759ee42e143ec5bcd5a806c71b4037dc1384a6f',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/apple_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/apple_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d759ee42e143ec5bcd5a806c71b4037dc1384a6f',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/apple_200.png',
    },
  },
  {
    name: 'apple_32.png',
    path: 'src/img/apple_32.png',
    sha: 'a8bc36cbd9c18c159a4517dd0f7e4ebff75b9e32',
    size: 2132,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/apple_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/apple_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a8bc36cbd9c18c159a4517dd0f7e4ebff75b9e32',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/apple_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/apple_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a8bc36cbd9c18c159a4517dd0f7e4ebff75b9e32',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/apple_32.png',
    },
  },
  {
    name: 'bannon_200.png',
    path: 'src/img/bannon_200.png',
    sha: 'bdf6f6e731c89eb7597e143dad26bf11588665b6',
    size: 36654,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/bannon_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/bannon_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/bdf6f6e731c89eb7597e143dad26bf11588665b6',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/bannon_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/bannon_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/bdf6f6e731c89eb7597e143dad26bf11588665b6',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/bannon_200.png',
    },
  },
  {
    name: 'bannon_32.png',
    path: 'src/img/bannon_32.png',
    sha: '2d703d1ade810435e0ee6f8504826b81a9294c89',
    size: 1817,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/bannon_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/bannon_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/2d703d1ade810435e0ee6f8504826b81a9294c89',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/bannon_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/bannon_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/2d703d1ade810435e0ee6f8504826b81a9294c89',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/bannon_32.png',
    },
  },
  {
    name: 'buchanan_200.png',
    path: 'src/img/buchanan_200.png',
    sha: '70c9fba2477feaa12da3830596f1531f1ee592a7',
    size: 31989,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/buchanan_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/buchanan_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/70c9fba2477feaa12da3830596f1531f1ee592a7',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/buchanan_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/buchanan_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/70c9fba2477feaa12da3830596f1531f1ee592a7',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/buchanan_200.png',
    },
  },
  {
    name: 'buchanan_32.png',
    path: 'src/img/buchanan_32.png',
    sha: '9cc250401be042bd60f5ea3ab3b191ce1cc9b213',
    size: 1694,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/buchanan_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/buchanan_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/9cc250401be042bd60f5ea3ab3b191ce1cc9b213',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/buchanan_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/buchanan_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/9cc250401be042bd60f5ea3ab3b191ce1cc9b213',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/buchanan_32.png',
    },
  },
  {
    name: 'bush_200.png',
    path: 'src/img/bush_200.png',
    sha: '8922aaf99a77d344773a2d76993232c9d7331fe6',
    size: 26577,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/bush_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/bush_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/8922aaf99a77d344773a2d76993232c9d7331fe6',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/bush_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/bush_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/8922aaf99a77d344773a2d76993232c9d7331fe6',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/bush_200.png',
    },
  },
  {
    name: 'bush_32.png',
    path: 'src/img/bush_32.png',
    sha: 'b2f69614bbfdb810aed4a03f8b4a40dc2649d7c1',
    size: 1683,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/bush_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/bush_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/b2f69614bbfdb810aed4a03f8b4a40dc2649d7c1',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/bush_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/bush_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/b2f69614bbfdb810aed4a03f8b4a40dc2649d7c1',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/bush_32.png',
    },
  },
  {
    name: 'candle_200.gif',
    path: 'src/img/candle_200.gif',
    sha: '53df90c9a6c9a696b62b96c18f8f24fb45b15d5a',
    size: 37464,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/candle_200.gif?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/candle_200.gif',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/53df90c9a6c9a696b62b96c18f8f24fb45b15d5a',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/candle_200.gif',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/candle_200.gif?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/53df90c9a6c9a696b62b96c18f8f24fb45b15d5a',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/candle_200.gif',
    },
  },
  {
    name: 'candle_200.png',
    path: 'src/img/candle_200.png',
    sha: '0b4037849c5124a855fcf9357311ed02895c7087',
    size: 10461,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/candle_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/candle_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/0b4037849c5124a855fcf9357311ed02895c7087',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/candle_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/candle_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/0b4037849c5124a855fcf9357311ed02895c7087',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/candle_200.png',
    },
  },
  {
    name: 'candle_32.png',
    path: 'src/img/candle_32.png',
    sha: '764ff0e9e9fc721281222d034ce4e75819356c6e',
    size: 1603,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/candle_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/candle_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/764ff0e9e9fc721281222d034ce4e75819356c6e',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/candle_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/candle_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/764ff0e9e9fc721281222d034ce4e75819356c6e',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/candle_32.png',
    },
  },
  {
    name: 'cheney_200.png',
    path: 'src/img/cheney_200.png',
    sha: '7b1d2d3d8029274ffc7813b369c8b84711184797',
    size: 26829,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cheney_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cheney_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/7b1d2d3d8029274ffc7813b369c8b84711184797',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cheney_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cheney_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/7b1d2d3d8029274ffc7813b369c8b84711184797',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cheney_200.png',
    },
  },
  {
    name: 'cheney_32.png',
    path: 'src/img/cheney_32.png',
    sha: '20fcbae8be81ca99315e339cb392cbf15ea04325',
    size: 1696,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cheney_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cheney_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/20fcbae8be81ca99315e339cb392cbf15ea04325',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cheney_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cheney_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/20fcbae8be81ca99315e339cb392cbf15ea04325',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cheney_32.png',
    },
  },
  {
    name: 'cherries_200.png',
    path: 'src/img/cherries_200.png',
    sha: '787d2056e5e70646694a7898631dba0527a43223',
    size: 17489,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cherries_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cherries_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/787d2056e5e70646694a7898631dba0527a43223',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cherries_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cherries_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/787d2056e5e70646694a7898631dba0527a43223',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cherries_200.png',
    },
  },
  {
    name: 'cherries_32.png',
    path: 'src/img/cherries_32.png',
    sha: '514207f38436216b2835212f27c0a37d132a181a',
    size: 1826,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cherries_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cherries_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/514207f38436216b2835212f27c0a37d132a181a',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cherries_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cherries_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/514207f38436216b2835212f27c0a37d132a181a',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cherries_32.png',
    },
  },
  {
    name: 'christie_200.png',
    path: 'src/img/christie_200.png',
    sha: 'a255daa9d119ac4124e99f901830b0d632782c27',
    size: 28589,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/christie_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/christie_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a255daa9d119ac4124e99f901830b0d632782c27',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/christie_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/christie_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a255daa9d119ac4124e99f901830b0d632782c27',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/christie_200.png',
    },
  },
  {
    name: 'christie_32.png',
    path: 'src/img/christie_32.png',
    sha: 'e74f70299d6d9080b3f5eb2a51c168b7729da355',
    size: 1618,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/christie_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/christie_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/e74f70299d6d9080b3f5eb2a51c168b7729da355',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/christie_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/christie_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/e74f70299d6d9080b3f5eb2a51c168b7729da355',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/christie_32.png',
    },
  },
  {
    name: 'crimson-avenger_200.png',
    path: 'src/img/crimson-avenger_200.png',
    sha: '86d1b9ee7f7016583f58aa8e4e29304ea2ebdbf6',
    size: 97751,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/crimson-avenger_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/crimson-avenger_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/86d1b9ee7f7016583f58aa8e4e29304ea2ebdbf6',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/crimson-avenger_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/crimson-avenger_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/86d1b9ee7f7016583f58aa8e4e29304ea2ebdbf6',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/crimson-avenger_200.png',
    },
  },
  {
    name: 'crimson-avenger_32_c.png',
    path: 'src/img/crimson-avenger_32_c.png',
    sha: '79653f74b83e991f7af2ee4512cd2ea7669ab505',
    size: 2837,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/crimson-avenger_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/crimson-avenger_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/79653f74b83e991f7af2ee4512cd2ea7669ab505',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/crimson-avenger_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/crimson-avenger_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/79653f74b83e991f7af2ee4512cd2ea7669ab505',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/crimson-avenger_32_c.png',
    },
  },
  {
    name: 'cruz_200.png',
    path: 'src/img/cruz_200.png',
    sha: 'b8ece1449c9bab3af0a6bd6432ee1a8301e94fa0',
    size: 30779,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cruz_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cruz_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/b8ece1449c9bab3af0a6bd6432ee1a8301e94fa0',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cruz_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cruz_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/b8ece1449c9bab3af0a6bd6432ee1a8301e94fa0',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cruz_200.png',
    },
  },
  {
    name: 'cruz_32.png',
    path: 'src/img/cruz_32.png',
    sha: 'cfde725dcc85cc43920bb7843ee1e961c3264d20',
    size: 1691,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cruz_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cruz_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/cfde725dcc85cc43920bb7843ee1e961c3264d20',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cruz_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cruz_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/cfde725dcc85cc43920bb7843ee1e961c3264d20',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cruz_32.png',
    },
  },
  {
    name: 'cupcake_200.png',
    path: 'src/img/cupcake_200.png',
    sha: 'e7e552600e9620833807cbd603637ad2f4a5d641',
    size: 29246,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cupcake_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cupcake_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/e7e552600e9620833807cbd603637ad2f4a5d641',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cupcake_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cupcake_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/e7e552600e9620833807cbd603637ad2f4a5d641',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cupcake_200.png',
    },
  },
  {
    name: 'cupcake_32.png',
    path: 'src/img/cupcake_32.png',
    sha: '4c9fa2fea14df98855d1f333f0928770d1931115',
    size: 2066,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cupcake_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cupcake_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4c9fa2fea14df98855d1f333f0928770d1931115',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cupcake_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/cupcake_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4c9fa2fea14df98855d1f333f0928770d1931115',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/cupcake_32.png',
    },
  },
  {
    name: 'devi_200.png',
    path: 'src/img/devi_200.png',
    sha: '5840f80e21ef75e99b194a8524b4a1d6d83e9e5d',
    size: 98138,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/devi_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/devi_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/5840f80e21ef75e99b194a8524b4a1d6d83e9e5d',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/devi_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/devi_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/5840f80e21ef75e99b194a8524b4a1d6d83e9e5d',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/devi_200.png',
    },
  },
  {
    name: 'devi_32_c.png',
    path: 'src/img/devi_32_c.png',
    sha: '68a5ab1793eb770df03ae9c303b0803ccfb7de8f',
    size: 2646,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/devi_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/devi_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/68a5ab1793eb770df03ae9c303b0803ccfb7de8f',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/devi_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/devi_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/68a5ab1793eb770df03ae9c303b0803ccfb7de8f',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/devi_32_c.png',
    },
  },
  {
    name: 'donald-trump_200.gif',
    path: 'src/img/donald-trump_200.gif',
    sha: '725903fcba797d69331e577303a6664718d0d19f',
    size: 32955,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donald-trump_200.gif?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donald-trump_200.gif',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/725903fcba797d69331e577303a6664718d0d19f',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/donald-trump_200.gif',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donald-trump_200.gif?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/725903fcba797d69331e577303a6664718d0d19f',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donald-trump_200.gif',
    },
  },
  {
    name: 'donald-trump_200.png',
    path: 'src/img/donald-trump_200.png',
    sha: 'ae53431a706cfb9ff2611bb6d0af5e1b37f06cfd',
    size: 33637,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donald-trump_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donald-trump_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/ae53431a706cfb9ff2611bb6d0af5e1b37f06cfd',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/donald-trump_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donald-trump_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/ae53431a706cfb9ff2611bb6d0af5e1b37f06cfd',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donald-trump_200.png',
    },
  },
  {
    name: 'donald-trump_64.gif',
    path: 'src/img/donald-trump_64.gif',
    sha: '29593b2c6dfdba753fbc5aec59ac483c1c133dbe',
    size: 6437,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donald-trump_64.gif?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donald-trump_64.gif',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/29593b2c6dfdba753fbc5aec59ac483c1c133dbe',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/donald-trump_64.gif',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donald-trump_64.gif?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/29593b2c6dfdba753fbc5aec59ac483c1c133dbe',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donald-trump_64.gif',
    },
  },
  {
    name: 'donald-trump_64.png',
    path: 'src/img/donald-trump_64.png',
    sha: '360bce4eaa6aca3fbe93962db8e32586bff430d8',
    size: 5054,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donald-trump_64.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donald-trump_64.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/360bce4eaa6aca3fbe93962db8e32586bff430d8',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/donald-trump_64.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donald-trump_64.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/360bce4eaa6aca3fbe93962db8e32586bff430d8',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donald-trump_64.png',
    },
  },
  {
    name: 'donut_200.png',
    path: 'src/img/donut_200.png',
    sha: 'a5c6a563dfb27608972d938b69afa7af620d771a',
    size: 12219,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donut_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donut_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a5c6a563dfb27608972d938b69afa7af620d771a',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/donut_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donut_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a5c6a563dfb27608972d938b69afa7af620d771a',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donut_200.png',
    },
  },
  {
    name: 'donut_32.png',
    path: 'src/img/donut_32.png',
    sha: '66b7491a08522fe467a8668acb8aae6efe1b148e',
    size: 1758,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donut_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donut_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/66b7491a08522fe467a8668acb8aae6efe1b148e',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/donut_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/donut_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/66b7491a08522fe467a8668acb8aae6efe1b148e',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/donut_32.png',
    },
  },
  {
    name: 'dust_200.png',
    path: 'src/img/dust_200.png',
    sha: 'a30294a8a7e78af6458571d1af5c35b664e9a750',
    size: 47673,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/dust_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/dust_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a30294a8a7e78af6458571d1af5c35b664e9a750',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/dust_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/dust_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a30294a8a7e78af6458571d1af5c35b664e9a750',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/dust_200.png',
    },
  },
  {
    name: 'dust_32_c.png',
    path: 'src/img/dust_32_c.png',
    sha: '1cd3b791d709c8b491636fddaf08490c7ce5276b',
    size: 2143,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/dust_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/dust_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/1cd3b791d709c8b491636fddaf08490c7ce5276b',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/dust_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/dust_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/1cd3b791d709c8b491636fddaf08490c7ce5276b',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/dust_32_c.png',
    },
  },
  {
    name: 'fries_200.png',
    path: 'src/img/fries_200.png',
    sha: 'ad2e3121275254a084b840fc67152b5360c3f9b5',
    size: 31429,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/fries_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/fries_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/ad2e3121275254a084b840fc67152b5360c3f9b5',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/fries_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/fries_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/ad2e3121275254a084b840fc67152b5360c3f9b5',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/fries_200.png',
    },
  },
  {
    name: 'fries_32.png',
    path: 'src/img/fries_32.png',
    sha: 'd6c34f9fda262291f8d574b140824ed30380a646',
    size: 2137,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/fries_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/fries_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d6c34f9fda262291f8d574b140824ed30380a646',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/fries_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/fries_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d6c34f9fda262291f8d574b140824ed30380a646',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/fries_32.png',
    },
  },
  {
    name: 'grace-choi_200.png',
    path: 'src/img/grace-choi_200.png',
    sha: 'aaf1eb4a86c426ff7530397dfc1009f7fac8cab1',
    size: 93435,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/grace-choi_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/grace-choi_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/aaf1eb4a86c426ff7530397dfc1009f7fac8cab1',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/grace-choi_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/grace-choi_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/aaf1eb4a86c426ff7530397dfc1009f7fac8cab1',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/grace-choi_200.png',
    },
  },
  {
    name: 'grace-choi_32_c.png',
    path: 'src/img/grace-choi_32_c.png',
    sha: '4cf2c2112560940a872dfed7aabc96c1341dbdcd',
    size: 2663,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/grace-choi_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/grace-choi_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4cf2c2112560940a872dfed7aabc96c1341dbdcd',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/grace-choi_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/grace-choi_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4cf2c2112560940a872dfed7aabc96c1341dbdcd',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/grace-choi_32_c.png',
    },
  },
  {
    name: 'hamburger_200.png',
    path: 'src/img/hamburger_200.png',
    sha: 'f9662651eed4cd6696fdcde2c648bff4a2712e25',
    size: 27718,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/hamburger_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/hamburger_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/f9662651eed4cd6696fdcde2c648bff4a2712e25',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/hamburger_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/hamburger_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/f9662651eed4cd6696fdcde2c648bff4a2712e25',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/hamburger_200.png',
    },
  },
  {
    name: 'hamburger_32.png',
    path: 'src/img/hamburger_32.png',
    sha: 'b63508da810ca0e9f89f0afde433a5367098c159',
    size: 2276,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/hamburger_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/hamburger_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/b63508da810ca0e9f89f0afde433a5367098c159',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/hamburger_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/hamburger_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/b63508da810ca0e9f89f0afde433a5367098c159',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/hamburger_32.png',
    },
  },
  {
    name: 'hatch_200.png',
    path: 'src/img/hatch_200.png',
    sha: 'f835fe745c5cc74a55353ca24bd791a84d75a73c',
    size: 33913,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/hatch_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/hatch_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/f835fe745c5cc74a55353ca24bd791a84d75a73c',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/hatch_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/hatch_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/f835fe745c5cc74a55353ca24bd791a84d75a73c',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/hatch_200.png',
    },
  },
  {
    name: 'hatch_32.png',
    path: 'src/img/hatch_32.png',
    sha: 'd4346321b9266f6b47a1fb4b92b470b241a27fbc',
    size: 1781,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/hatch_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/hatch_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d4346321b9266f6b47a1fb4b92b470b241a27fbc',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/hatch_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/hatch_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d4346321b9266f6b47a1fb4b92b470b241a27fbc',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/hatch_32.png',
    },
  },
  {
    name: 'heart.png',
    path: 'src/img/heart.png',
    sha: '298656bb222af802c73b2d9e1c0a471b71b01898',
    size: 3021,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/heart.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/heart.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/298656bb222af802c73b2d9e1c0a471b71b01898',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/heart.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/heart.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/298656bb222af802c73b2d9e1c0a471b71b01898',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/heart.png',
    },
  },
  {
    name: 'ice-cream_200.png',
    path: 'src/img/ice-cream_200.png',
    sha: 'e2fd49aa42dd867130a5f52bc2d00aff18dbd5f6',
    size: 22289,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/ice-cream_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/ice-cream_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/e2fd49aa42dd867130a5f52bc2d00aff18dbd5f6',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/ice-cream_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/ice-cream_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/e2fd49aa42dd867130a5f52bc2d00aff18dbd5f6',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/ice-cream_200.png',
    },
  },
  {
    name: 'ice-cream_32.png',
    path: 'src/img/ice-cream_32.png',
    sha: '94bbddd157abb92113ed70749642ea4552399fa0',
    size: 1686,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/ice-cream_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/ice-cream_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/94bbddd157abb92113ed70749642ea4552399fa0',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/ice-cream_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/ice-cream_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/94bbddd157abb92113ed70749642ea4552399fa0',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/ice-cream_32.png',
    },
  },
  {
    name: 'jet_32_c.png',
    path: 'src/img/jet_32_c.png',
    sha: 'aad1b258f9419d4c19b8f3f7e4da2f403bfe22cb',
    size: 2609,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/jet_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/jet_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/aad1b258f9419d4c19b8f3f7e4da2f403bfe22cb',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/jet_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/jet_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/aad1b258f9419d4c19b8f3f7e4da2f403bfe22cb',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/jet_32_c.png',
    },
  },
  {
    name: 'key_200.gif',
    path: 'src/img/key_200.gif',
    sha: 'e3402cb015ff25e68ea8da1dd2e55242a7b1cb1e',
    size: 51022,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/key_200.gif?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/key_200.gif',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/e3402cb015ff25e68ea8da1dd2e55242a7b1cb1e',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/key_200.gif',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/key_200.gif?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/e3402cb015ff25e68ea8da1dd2e55242a7b1cb1e',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/key_200.gif',
    },
  },
  {
    name: 'key_200.png',
    path: 'src/img/key_200.png',
    sha: 'd5723f8873803db042653b49cf25a00a75fe5cb3',
    size: 47394,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/key_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/key_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d5723f8873803db042653b49cf25a00a75fe5cb3',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/key_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/key_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d5723f8873803db042653b49cf25a00a75fe5cb3',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/key_200.png',
    },
  },
  {
    name: 'key_32.png',
    path: 'src/img/key_32.png',
    sha: 'a4e798314ed9dcb503ac63f47989019e2998df1b',
    size: 1366,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/key_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/key_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a4e798314ed9dcb503ac63f47989019e2998df1b',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/key_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/key_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a4e798314ed9dcb503ac63f47989019e2998df1b',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/key_32.png',
    },
  },
  {
    name: 'kiwi_200.png',
    path: 'src/img/kiwi_200.png',
    sha: 'eb1ae5fa59d3160c1b80a3eb4e05a1dd38c03fee',
    size: 35841,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/kiwi_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/kiwi_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/eb1ae5fa59d3160c1b80a3eb4e05a1dd38c03fee',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/kiwi_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/kiwi_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/eb1ae5fa59d3160c1b80a3eb4e05a1dd38c03fee',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/kiwi_200.png',
    },
  },
  {
    name: 'kiwi_32.png',
    path: 'src/img/kiwi_32.png',
    sha: '435b080f321e89f0c25210aca527b515d36b3c3e',
    size: 2550,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/kiwi_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/kiwi_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/435b080f321e89f0c25210aca527b515d36b3c3e',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/kiwi_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/kiwi_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/435b080f321e89f0c25210aca527b515d36b3c3e',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/kiwi_32.png',
    },
  },
  {
    name: 'la-borinquena_200.png',
    path: 'src/img/la-borinquena_200.png',
    sha: '0fb6b0745a74defc1db02e3c92061d5ecd913caf',
    size: 101307,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/la-borinquena_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/la-borinquena_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/0fb6b0745a74defc1db02e3c92061d5ecd913caf',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/la-borinquena_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/la-borinquena_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/0fb6b0745a74defc1db02e3c92061d5ecd913caf',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/la-borinquena_200.png',
    },
  },
  {
    name: 'la-borinquena_32_c.png',
    path: 'src/img/la-borinquena_32_c.png',
    sha: 'bf7dd07cab67f47b54f5362235e5b90cba144541',
    size: 2920,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/la-borinquena_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/la-borinquena_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/bf7dd07cab67f47b54f5362235e5b90cba144541',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/la-borinquena_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/la-borinquena_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/bf7dd07cab67f47b54f5362235e5b90cba144541',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/la-borinquena_32_c.png',
    },
  },
  {
    name: 'mcconnell_200.png',
    path: 'src/img/mcconnell_200.png',
    sha: '3e131c0571f523492a8d0799bb77d079f9eb4433',
    size: 29133,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/mcconnell_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/mcconnell_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/3e131c0571f523492a8d0799bb77d079f9eb4433',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/mcconnell_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/mcconnell_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/3e131c0571f523492a8d0799bb77d079f9eb4433',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/mcconnell_200.png',
    },
  },
  {
    name: 'mcconnell_32.png',
    path: 'src/img/mcconnell_32.png',
    sha: '28f0291bdb59dad5f79b589ef323ced3562bd3fa',
    size: 1480,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/mcconnell_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/mcconnell_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/28f0291bdb59dad5f79b589ef323ced3562bd3fa',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/mcconnell_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/mcconnell_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/28f0291bdb59dad5f79b589ef323ced3562bd3fa',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/mcconnell_32.png',
    },
  },
  {
    name: 'misty-knight_200.png',
    path: 'src/img/misty-knight_200.png',
    sha: '2cf01cf3f9ccc38a8909838a2a0331f9cf79d822',
    size: 65552,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/misty-knight_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/misty-knight_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/2cf01cf3f9ccc38a8909838a2a0331f9cf79d822',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/misty-knight_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/misty-knight_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/2cf01cf3f9ccc38a8909838a2a0331f9cf79d822',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/misty-knight_200.png',
    },
  },
  {
    name: 'misty-knight_32_c.png',
    path: 'src/img/misty-knight_32_c.png',
    sha: '1e41826bad23249db63ad14e0cc0aedfa2a9f183',
    size: 2432,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/misty-knight_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/misty-knight_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/1e41826bad23249db63ad14e0cc0aedfa2a9f183',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/misty-knight_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/misty-knight_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/1e41826bad23249db63ad14e0cc0aedfa2a9f183',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/misty-knight_32_c.png',
    },
  },
  {
    name: 'monet-st-croix_200.png',
    path: 'src/img/monet-st-croix_200.png',
    sha: '65d2317c77106482891a3faee80a4255ea00eee5',
    size: 88686,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/monet-st-croix_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/monet-st-croix_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/65d2317c77106482891a3faee80a4255ea00eee5',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/monet-st-croix_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/monet-st-croix_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/65d2317c77106482891a3faee80a4255ea00eee5',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/monet-st-croix_200.png',
    },
  },
  {
    name: 'monet-st-croix_32_c.png',
    path: 'src/img/monet-st-croix_32_c.png',
    sha: '79eb61b35ff994fa41ab1e02a1dab5a4384ecba0',
    size: 2548,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/monet-st-croix_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/monet-st-croix_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/79eb61b35ff994fa41ab1e02a1dab5a4384ecba0',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/monet-st-croix_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/monet-st-croix_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/79eb61b35ff994fa41ab1e02a1dab5a4384ecba0',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/monet-st-croix_32_c.png',
    },
  },
  {
    name: 'monica-chang_200.png',
    path: 'src/img/monica-chang_200.png',
    sha: '4e1fe366ece445f771bdd7f0e5d3314515b8f5dc',
    size: 76210,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/monica-chang_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/monica-chang_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4e1fe366ece445f771bdd7f0e5d3314515b8f5dc',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/monica-chang_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/monica-chang_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4e1fe366ece445f771bdd7f0e5d3314515b8f5dc',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/monica-chang_200.png',
    },
  },
  {
    name: 'monica-chang_32_c.png',
    path: 'src/img/monica-chang_32_c.png',
    sha: '2d3554ae8af538c1e55017f0422717e91520ca38',
    size: 2360,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/monica-chang_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/monica-chang_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/2d3554ae8af538c1e55017f0422717e91520ca38',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/monica-chang_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/monica-chang_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/2d3554ae8af538c1e55017f0422717e91520ca38',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/monica-chang_32_c.png',
    },
  },
  {
    name: 'ms-marvel_200.png',
    path: 'src/img/ms-marvel_200.png',
    sha: '72bd18691d22ee44ecb95f225af0d452ffe633ff',
    size: 79983,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/ms-marvel_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/ms-marvel_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/72bd18691d22ee44ecb95f225af0d452ffe633ff',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/ms-marvel_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/ms-marvel_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/72bd18691d22ee44ecb95f225af0d452ffe633ff',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/ms-marvel_200.png',
    },
  },
  {
    name: 'ms-marvel_32_c.png',
    path: 'src/img/ms-marvel_32_c.png',
    sha: '6bdfbe95f95eab2070956fae86b3f149b3341cc2',
    size: 2602,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/ms-marvel_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/ms-marvel_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/6bdfbe95f95eab2070956fae86b3f149b3341cc2',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/ms-marvel_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/ms-marvel_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/6bdfbe95f95eab2070956fae86b3f149b3341cc2',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/ms-marvel_32_c.png',
    },
  },
  {
    name: 'nubia_200.png',
    path: 'src/img/nubia_200.png',
    sha: '6809c1920d1dd2715e0f77ce1b0f4ea7e6b4c80e',
    size: 75247,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/nubia_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/nubia_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/6809c1920d1dd2715e0f77ce1b0f4ea7e6b4c80e',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/nubia_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/nubia_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/6809c1920d1dd2715e0f77ce1b0f4ea7e6b4c80e',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/nubia_200.png',
    },
  },
  {
    name: 'nubia_32_c.png',
    path: 'src/img/nubia_32_c.png',
    sha: '4d6453372145a673f5830ffdd57466c81c40a4b4',
    size: 2793,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/nubia_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/nubia_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4d6453372145a673f5830ffdd57466c81c40a4b4',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/nubia_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/nubia_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4d6453372145a673f5830ffdd57466c81c40a4b4',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/nubia_32_c.png',
    },
  },
  {
    name: 'padlock_200.gif',
    path: 'src/img/padlock_200.gif',
    sha: 'a5c88ede71faccf491076e84046644fc4217ba56',
    size: 44214,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/padlock_200.gif?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/padlock_200.gif',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a5c88ede71faccf491076e84046644fc4217ba56',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/padlock_200.gif',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/padlock_200.gif?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a5c88ede71faccf491076e84046644fc4217ba56',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/padlock_200.gif',
    },
  },
  {
    name: 'padlock_32.png',
    path: 'src/img/padlock_32.png',
    sha: 'a31091038f99755b9766d5de030fbc5810d673c5',
    size: 484,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/padlock_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/padlock_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a31091038f99755b9766d5de030fbc5810d673c5',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/padlock_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/padlock_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a31091038f99755b9766d5de030fbc5810d673c5',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/padlock_32.png',
    },
  },
  {
    name: 'pear_200.png',
    path: 'src/img/pear_200.png',
    sha: 'fa7ece78d0553e98f3c7ce6377de4389ff0f33ad',
    size: 21840,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/pear_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/pear_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/fa7ece78d0553e98f3c7ce6377de4389ff0f33ad',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/pear_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/pear_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/fa7ece78d0553e98f3c7ce6377de4389ff0f33ad',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/pear_200.png',
    },
  },
  {
    name: 'pear_32.png',
    path: 'src/img/pear_32.png',
    sha: '61419d21546be277a9d1544d9f4334daadfa0309',
    size: 1848,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/pear_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/pear_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/61419d21546be277a9d1544d9f4334daadfa0309',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/pear_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/pear_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/61419d21546be277a9d1544d9f4334daadfa0309',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/pear_32.png',
    },
  },
  {
    name: 'plum_200.png',
    path: 'src/img/plum_200.png',
    sha: 'd11812491ca18869cd77b36f7a4a6ea40fbd1915',
    size: 20628,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/plum_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/plum_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d11812491ca18869cd77b36f7a4a6ea40fbd1915',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/plum_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/plum_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d11812491ca18869cd77b36f7a4a6ea40fbd1915',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/plum_200.png',
    },
  },
  {
    name: 'plum_32.png',
    path: 'src/img/plum_32.png',
    sha: '04b09d04046c5f6b2679bb4adb0acb4d07c1adc2',
    size: 2066,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/plum_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/plum_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/04b09d04046c5f6b2679bb4adb0acb4d07c1adc2',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/plum_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/plum_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/04b09d04046c5f6b2679bb4adb0acb4d07c1adc2',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/plum_32.png',
    },
  },
  {
    name: 'popsicle_200.png',
    path: 'src/img/popsicle_200.png',
    sha: '3cae89bac0975adf9fe295cbcd88584fcd1e0c1c',
    size: 19036,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/popsicle_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/popsicle_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/3cae89bac0975adf9fe295cbcd88584fcd1e0c1c',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/popsicle_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/popsicle_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/3cae89bac0975adf9fe295cbcd88584fcd1e0c1c',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/popsicle_200.png',
    },
  },
  {
    name: 'popsicle_32.png',
    path: 'src/img/popsicle_32.png',
    sha: 'cb54b15b0b187b8db2c6240d6818e91467bd98c2',
    size: 1964,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/popsicle_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/popsicle_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/cb54b15b0b187b8db2c6240d6818e91467bd98c2',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/popsicle_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/popsicle_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/cb54b15b0b187b8db2c6240d6818e91467bd98c2',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/popsicle_32.png',
    },
  },
  {
    name: 'rainbow.png',
    path: 'src/img/rainbow.png',
    sha: '55e94fc0dc7053edca1d12e82bc218f5f80463b5',
    size: 30668,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/rainbow.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/rainbow.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/55e94fc0dc7053edca1d12e82bc218f5f80463b5',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/rainbow.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/rainbow.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/55e94fc0dc7053edca1d12e82bc218f5f80463b5',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/rainbow.png',
    },
  },
  {
    name: 'raspberry_200.png',
    path: 'src/img/raspberry_200.png',
    sha: '81119c16ecd76e7562d3875d8062b8236d5f2c9c',
    size: 23223,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/raspberry_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/raspberry_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/81119c16ecd76e7562d3875d8062b8236d5f2c9c',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/raspberry_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/raspberry_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/81119c16ecd76e7562d3875d8062b8236d5f2c9c',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/raspberry_200.png',
    },
  },
  {
    name: 'raspberry_32.png',
    path: 'src/img/raspberry_32.png',
    sha: '69562197d8e1c50509fe7020948ba7a02c29c8ae',
    size: 2065,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/raspberry_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/raspberry_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/69562197d8e1c50509fe7020948ba7a02c29c8ae',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/raspberry_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/raspberry_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/69562197d8e1c50509fe7020948ba7a02c29c8ae',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/raspberry_32.png',
    },
  },
  {
    name: 'reagan_200.png',
    path: 'src/img/reagan_200.png',
    sha: 'fd8de653d0e051874df9552703ada6ed82d40441',
    size: 29994,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/reagan_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/reagan_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/fd8de653d0e051874df9552703ada6ed82d40441',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/reagan_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/reagan_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/fd8de653d0e051874df9552703ada6ed82d40441',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/reagan_200.png',
    },
  },
  {
    name: 'reagan_32.png',
    path: 'src/img/reagan_32.png',
    sha: 'd61f3093de5763b6d7a88eb0e9a60e3915ff648f',
    size: 1586,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/reagan_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/reagan_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d61f3093de5763b6d7a88eb0e9a60e3915ff648f',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/reagan_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/reagan_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d61f3093de5763b6d7a88eb0e9a60e3915ff648f',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/reagan_32.png',
    },
  },
  {
    name: 'rove_200.png',
    path: 'src/img/rove_200.png',
    sha: '6bf6b67fcb9cd7a06792a9e2b4e9e4d10273940e',
    size: 27319,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/rove_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/rove_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/6bf6b67fcb9cd7a06792a9e2b4e9e4d10273940e',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/rove_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/rove_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/6bf6b67fcb9cd7a06792a9e2b4e9e4d10273940e',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/rove_200.png',
    },
  },
  {
    name: 'rove_32.png',
    path: 'src/img/rove_32.png',
    sha: 'bd6523e643b16b7d4e32fd515b2ea77d4cb1aeef',
    size: 1680,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/rove_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/rove_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/bd6523e643b16b7d4e32fd515b2ea77d4cb1aeef',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/rove_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/rove_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/bd6523e643b16b7d4e32fd515b2ea77d4cb1aeef',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/rove_32.png',
    },
  },
  {
    name: 'silk_200.png',
    path: 'src/img/silk_200.png',
    sha: '45f771286d56d840cb0a8cf5f2d8164022020e98',
    size: 63383,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/silk_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/silk_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/45f771286d56d840cb0a8cf5f2d8164022020e98',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/silk_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/silk_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/45f771286d56d840cb0a8cf5f2d8164022020e98',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/silk_200.png',
    },
  },
  {
    name: 'silk_32_c.png',
    path: 'src/img/silk_32_c.png',
    sha: '9b68c3de7e0184cc09110627fc1266f196411737',
    size: 2600,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/silk_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/silk_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/9b68c3de7e0184cc09110627fc1266f196411737',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/silk_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/silk_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/9b68c3de7e0184cc09110627fc1266f196411737',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/silk_32_c.png',
    },
  },
  {
    name: 'spencer_200.png',
    path: 'src/img/spencer_200.png',
    sha: '875cd4b0c2a9434efb1f2f6efd3b151acbe5f3a7',
    size: 23041,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/spencer_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/spencer_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/875cd4b0c2a9434efb1f2f6efd3b151acbe5f3a7',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/spencer_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/spencer_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/875cd4b0c2a9434efb1f2f6efd3b151acbe5f3a7',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/spencer_200.png',
    },
  },
  {
    name: 'spencer_32.png',
    path: 'src/img/spencer_32.png',
    sha: 'c909e0c6dc20a90c82a4e3ba2f91dfd29b856113',
    size: 1514,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/spencer_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/spencer_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/c909e0c6dc20a90c82a4e3ba2f91dfd29b856113',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/spencer_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/spencer_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/c909e0c6dc20a90c82a4e3ba2f91dfd29b856113',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/spencer_32.png',
    },
  },
  {
    name: 'staircase_200.png',
    path: 'src/img/staircase_200.png',
    sha: 'd35f1e9c49b91f3d074aa4e716ccad6e823ad122',
    size: 53656,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/staircase_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/staircase_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d35f1e9c49b91f3d074aa4e716ccad6e823ad122',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/staircase_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/staircase_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/d35f1e9c49b91f3d074aa4e716ccad6e823ad122',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/staircase_200.png',
    },
  },
  {
    name: 'staircase_32.png',
    path: 'src/img/staircase_32.png',
    sha: 'f3d51f5bd43ad8254a4113d8f81153728c7c87b7',
    size: 2696,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/staircase_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/staircase_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/f3d51f5bd43ad8254a4113d8f81153728c7c87b7',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/staircase_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/staircase_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/f3d51f5bd43ad8254a4113d8f81153728c7c87b7',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/staircase_32.png',
    },
  },
  {
    name: 'staircase_32_c.png',
    path: 'src/img/staircase_32_c.png',
    sha: 'adced44dd8b0f938c461a46d964302e9fde28056',
    size: 17937,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/staircase_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/staircase_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/adced44dd8b0f938c461a46d964302e9fde28056',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/staircase_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/staircase_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/adced44dd8b0f938c461a46d964302e9fde28056',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/staircase_32_c.png',
    },
  },
  {
    name: 'storm_200.png',
    path: 'src/img/storm_200.png',
    sha: '7545888264dc86be37094c649ebda190b1274542',
    size: 73209,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/storm_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/storm_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/7545888264dc86be37094c649ebda190b1274542',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/storm_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/storm_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/7545888264dc86be37094c649ebda190b1274542',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/storm_200.png',
    },
  },
  {
    name: 'storm_32_c.png',
    path: 'src/img/storm_32_c.png',
    sha: '78fbf88a3c7aa3dfce51b4558da5e4a8481160f4',
    size: 2297,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/storm_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/storm_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/78fbf88a3c7aa3dfce51b4558da5e4a8481160f4',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/storm_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/storm_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/78fbf88a3c7aa3dfce51b4558da5e4a8481160f4',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/storm_32_c.png',
    },
  },
  {
    name: 'sufganiyah_200.png',
    path: 'src/img/sufganiyah_200.png',
    sha: 'f4dbc931fe723d6b1f7fca13b6891965e98015b6',
    size: 25678,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/sufganiyah_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/sufganiyah_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/f4dbc931fe723d6b1f7fca13b6891965e98015b6',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/sufganiyah_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/sufganiyah_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/f4dbc931fe723d6b1f7fca13b6891965e98015b6',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/sufganiyah_200.png',
    },
  },
  {
    name: 'sufganiyah_32.png',
    path: 'src/img/sufganiyah_32.png',
    sha: '09faded0c8c5ffb867e0004750ec64bc954fb4fd',
    size: 1810,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/sufganiyah_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/sufganiyah_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/09faded0c8c5ffb867e0004750ec64bc954fb4fd',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/sufganiyah_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/sufganiyah_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/09faded0c8c5ffb867e0004750ec64bc954fb4fd',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/sufganiyah_32.png',
    },
  },
  {
    name: 'walker_200.png',
    path: 'src/img/walker_200.png',
    sha: 'add8e1715113986d86f7dbc61da709df72156ea0',
    size: 33992,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/walker_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/walker_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/add8e1715113986d86f7dbc61da709df72156ea0',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/walker_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/walker_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/add8e1715113986d86f7dbc61da709df72156ea0',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/walker_200.png',
    },
  },
  {
    name: 'walker_32.png',
    path: 'src/img/walker_32.png',
    sha: 'a53bba76649e3bf44fe333becd0d84ecc8787768',
    size: 1748,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/walker_32.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/walker_32.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a53bba76649e3bf44fe333becd0d84ecc8787768',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/walker_32.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/walker_32.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/a53bba76649e3bf44fe333becd0d84ecc8787768',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/walker_32.png',
    },
  },
  {
    name: 'wonder-woman_200.png',
    path: 'src/img/wonder-woman_200.png',
    sha: '72a60ada4749f1cea4fc03a2ed201dee648c1258',
    size: 102188,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/wonder-woman_200.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/wonder-woman_200.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/72a60ada4749f1cea4fc03a2ed201dee648c1258',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/wonder-woman_200.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/wonder-woman_200.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/72a60ada4749f1cea4fc03a2ed201dee648c1258',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/wonder-woman_200.png',
    },
  },
  {
    name: 'wonder-woman_32_c.png',
    path: 'src/img/wonder-woman_32_c.png',
    sha: '6efffb5361392eba70cafd2ba71013c3bd639805',
    size: 2875,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/wonder-woman_32_c.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/wonder-woman_32_c.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/6efffb5361392eba70cafd2ba71013c3bd639805',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/wonder-woman_32_c.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/wonder-woman_32_c.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/6efffb5361392eba70cafd2ba71013c3bd639805',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/wonder-woman_32_c.png',
    },
  },
  {
    name: 'you-died.png',
    path: 'src/img/you-died.png',
    sha: '4e3f648d1d88c7badf37b573b00e5c816db7acb9',
    size: 3056,
    url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/you-died.png?ref=master',
    html_url: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/you-died.png',
    git_url: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4e3f648d1d88c7badf37b573b00e5c816db7acb9',
    download_url: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/you-died.png',
    type: 'file',
    _links: {
      self: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/contents/src/img/you-died.png?ref=master',
      git: 'https://api.github.com/repos/rifkegribenes/dungeon-crawler/git/blobs/4e3f648d1d88c7badf37b573b00e5c816db7acb9',
      html: 'https://github.com/rifkegribenes/dungeon-crawler/blob/master/src/img/you-died.png',
    },
  },
];

export default imageManifest;
