const monsterTypes = [
  {
    name: 'The Propped Up Corpse of Ronald Reagan',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'George W. Bush',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Dick Cheney',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Chris Christie',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Scott Walker',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Richard Nixon',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Rush Limbaugh',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Richard Spencer',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Pat Buchanan',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Orrin Hatch',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 21,
  },
  {
    name: 'Jeff Flake',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 25,
  },
  {
    name: 'Ted Cruz',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 31,
  },
  {
    name: 'Mitch McConnell',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 37,
  },
  {
    name: 'Steve Bannon',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    type: 'monster',
    damage: 43,
  },
];

export default monsterTypes;
