const monsterTypes = [
  {
    name: 'George W. Bush',
    bio: '',
    youDiedMsg: '',
    iconUrl: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/georgeBush-reddevil.gif',
    cardUrl: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/georgeBush-reddevil_200.gif',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Dick Cheney',
    bio: '',
    youDiedMsg: '',
    iconUrl: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cheney_red_fangs.gif',
    cardUrl: 'https://raw.githubusercontent.com/rifkegribenes/dungeon-crawler/master/src/img/cheney_red_fangs_200.gif',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Chris Christie',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Scott Walker',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 15,
  },
  {
    name: 'Richard Spencer',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 30,
  },
  {
    name: 'Pat Buchanan',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 30,
  },
  {
    name: 'Orrin Hatch',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 30,
  },
  {
    name: 'Jeff Flake',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 30,
  },
  {
    name: 'Ted Cruz',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 45,
  },
  {
    name: 'Mitch McConnell',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 45,
  },
  {
    name: 'Steve Bannon',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 45,
  },
  {
    name: 'The Propped Up Corpse of Ronald Reagan',
    bio: '',
    youDiedMsg: '',
    iconUrl: '',
    cardUrl: '',
    type: 'monster',
    damage: 45,
  },
];

export default monsterTypes;
